#!/usr/local/bin/python
from sys import path
from gi.repository import Gtk

installer = "/usr/local/lib/gbi/"
#path.append("/home/ericbsd/gbi/src/")
path.append(installer)

from gbiWindow import MainWindow
from partition_handler import partition_repos

def main():
    Gtk.main()
    return 0

if __name__ == "__main__":
    partition_repos()
    MainWindow()
    main()

